# 1. Usamos Node.js para construir la aplicación 📦
FROM node:20-slim

# 2. Creamos la carpeta de trabajo
WORKDIR /app

# 3. Copiamos los archivos de paquetes para instalar las dependencias
COPY package*.json ./

# 4. Instalamos las librerías de React
RUN npm install

# 5. Copiamos todo el código del frontend
COPY . .

# 6. Exponemos el puerto que usa Vite por defecto
EXPOSE 5173

# 7. Encendemos el modo desarrollo de Vite
CMD ["npm", "run", "dev", "--", "--host"]